name: pyre

on: [push]

jobs:
  pyre:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install cython
          python -m pip install flask flask_cors graphql-core typing_inspect
          python -m pip install pyre-check-nightly

      - name: Run Pyre
        continue-on-error: true
        run: |
          pyre --output=json check > errors.json

      - name: Expose Pyre Results
        uses: actions/upload-artifact@v2
        with:
          name: Pyre Results
          path: errors.json

      - name: Fail Command On Errors
        run: |
          if [ "$(cat errors.json)" != "[]" ]; then exit 1; fi