name: Regression Suite

on: [push, pull_request]

jobs:
  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Start MinIo Server
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minioadmin" \
                     -e "MINIO_SECRET_KEY=minioadmin" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data

      - name: Start GCS Emulator
        run: |
          docker run -d --name fake-gcs-server \
                     -p 9090:4443 \
                     fsouza/fake-gcs-server -scheme http

      - name: Run Regression Tests
        run: coverage run -m pytest 
        env:
          MINIO_END_POINT: 127.0.0.1:9000
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin

      - name: Check Coverage
        run: coverage report --include=mabel* --fail-under=85

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  mypy:
    name: Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          
      - name: Install Requirements
        run:  pip install mypy

      - name: Execute Test
        run: mypy mabel